import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { worksans } from '@/styles/fonts'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'GBG Web Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={worksans.className}>{children}</body>
    </html>
  )
}
